Import('*')

# Set the target executable.  
#
target = exe_name

# Select the source files
#
source_files = Glob('*.cpp')

# Set up any required libraries
env.Append( LIBS =['pthread',] )

env.Program(target, source_files)

